// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2026, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{ExcelDateTime, Format, Workbook, XlsxError};

// Test to demonstrate autofit with a formatted native date.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();
    worksheet.set_paper_size(9);

    let date_format = Format::new().set_num_format("[$-809]dd\\ mmm\\ yyyy");

    let date1 = ExcelDateTime::from_ymd(2026, 1, 1)?;

    worksheet.write_date_with_format(0, 0, &date1, &date_format)?;

    worksheet.autofit();

    workbook.save(filename)?;

    Ok(())
}

// Test to demonstrate autofit. With Chrono date.
#[cfg(feature = "chrono")]
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();
    worksheet.set_paper_size(9);

    let date_format = Format::new().set_num_format("[$-809]dd\\ mmm\\ yyyy");

    let date1 = chrono::NaiveDate::from_ymd_opt(2026, 1, 1).unwrap();

    worksheet.write_date_with_format(0, 0, date1, &date_format)?;

    worksheet.autofit();

    workbook.save(filename)?;

    Ok(())
}

// Test to demonstrate autofit. With jiff date.
#[cfg(feature = "jiff")]
fn create_new_xlsx_file_3(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();
    worksheet.set_paper_size(9);

    let date_format = Format::new().set_num_format("[$-809]dd\\ mmm\\ yyyy");

    let date1 = jiff::civil::date(2026, 1, 1);

    worksheet.write_date_with_format(0, 0, date1, &date_format)?;

    worksheet.autofit();

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_autofit_with_format05_1() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit_with_format05")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
#[cfg(feature = "chrono")]
fn test_autofit_with_format05_2() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit_with_format05")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
#[cfg(feature = "jiff")]
fn test_autofit_with_format05_3() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit_with_format05")
        .set_function(create_new_xlsx_file_3)
        .unique("3")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
