// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2026, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Format, Workbook, XlsxError};

// Test to demonstrate autofit with a formatted number.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    let format1 = Format::new().set_num_format("0.0");
    let format2 = Format::new().set_num_format("0.000");

    worksheet.write(0, 0, 1234.02)?;
    worksheet.write_number_with_format(0, 1, 1234.02, &format1)?;
    worksheet.write_number_with_format(0, 2, 1234.02, &format2)?;

    worksheet.autofit();

    worksheet.set_paper_size(9);

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_autofit_with_format01() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit_with_format01")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
