// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Image, Workbook, XlsxError};

// Test the fix for the centering bug #165.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    worksheet.set_column_width_pixels(0, 200)?;
    worksheet.set_row_height_pixels(0, 15)?;

    let image = Image::new("tests/input/images/red_20x11.png")?;

    worksheet.insert_image_fit_to_cell_centered(0, 0, &image)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_image_scale04() {
    let test_runner = common::TestRunner::new()
        .set_name("image_scale04")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
